server:
  port: 8082
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  application:
    name: rabbit-consumer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    consul:
      discovery:
        register: true
        service-name: rabbit-consumer
      host: localhost
      port: 8500
  h2:
    console:
      enabled: true

