server:
  port: 8081
spring:
  boot:
    admin:
      client:
        url: http://localhost:9999
  application:
    name: rabbit-producer
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  cloud:
    consul:
      discovery:
        register: true
        service-name: rabbit-producer
      host: localhost
      port: 8500

